---
title: "Basic_Statistics"
output: html_document
date: "2024-07-30"
---

```{r setup, include=FALSE}
if (!require('tidyverse')) install.packages('tidyverse')
if (!require('ggplot2')) install.packages('ggplot2')
if (!require('pwr')) install.packages('pwr')
if (!require('car')) install.packages('car')
if (!require('ggpubr')) install.packages('ggpubr')

library(tidyverse)
library(ggplot2)
library(pwr)
library(car)
library(MASS)
library(lmtest)
library(tseries)
library(ggfortify)
library(ggpubr)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()

knitr::opts_chunk$set(echo = TRUE)
```
```{r The Lady Tasting Tea}

# Create vector of 0-4 sucesses
x_dhyper <- seq(0, 4, by = 1)

# Apply dhyper function
# m = number of "successes" (milk-first)
# n = number of "failures" (tea-first)
# k = number of "draws" (choice of teacups prepared milk-first)

y_dhyper <- dhyper(x_dhyper, m = 4, n = 4, k = 4)   

# Make a dataframe
hg_df <- tibble(x_dhyper,y_dhyper)
hg_df

## Plot dhyper values

# basic plot
hypergeometric <- hg_df |>
  ggplot(aes(x = x_dhyper, y = y_dhyper)
         ) +
           geom_point()
hypergeometric

# barplot
hypergeometric <- hg_df |>
  ggplot(aes(x = x_dhyper, y = y_dhyper)
  ) +
  geom_bar(stat = "identity")
hypergeometric

#better barplot
hypergeometric <- hg_df |>
  ggplot(aes(x = x_dhyper, y = y_dhyper)
  ) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
  labs(
    title = "Hypergeometric Distribution of 4 trials",
    subtitle = "Dashed line indicates 0.05 probability level"
  ) +
  xlab("Successes") +
  ylab("Probability") +
  theme_bw()
hypergeometric
```
```{r Normal distribution and t-test}
#Create a sequence of 100 equally spaced numbers between -4 and 4
x <- seq(-4, 4, length=100)

#create a vector of values that shows the height of the probability distribution
#for each value in x
y <- dnorm(x, mean = 0, sd = 1)

#plot x and y

norm_df <- tibble(x,y)

norm_dist <- norm_df |>
  ggplot(
    aes(x=x, y=y)
  ) +
  geom_line() +
  geom_hline(yintercept = 0.05, linetype = "dashed", color = "red") +
  scale_x_continuous(name = "",
                     breaks = c(-3, -2, -1, 0, 1, 2, 3), 
                     labels = paste0(seq(-3,3,1), "\u03c3")
                     ) +
  theme_bw()
norm_dist

#generate a tibble of normally distributed tick weights (2 populations)
pop1=rnorm(100,18.2,1)
pop2=rnorm(100,20.2,2)
pop3=rnorm(100,20.4,1.5)

tickwts <- cbind(pop1,pop2,pop3)
View(tickwts)
tickwts <- as_tibble(tickwts)

#tickwts isn't tidy
tickwts <- as_tibble(tickwts) %>% 
  pivot_longer(
    everything(),
    names_to = "population",
    values_to = "weight_mg"
  ) %>%
  mutate(pop.f = as.factor(population)) %>%
  mutate(pop.f=case_match(pop.f, "pop1" ~ "1", "pop2" ~ "2", "pop3" ~ "3")) %>%
  mutate(pop.f=as.numeric(pop.f)) %>%
  arrange(population)

pop.f <- as.factor(tickwts$population)
case_match(pop.f, "pop1" ~ "1", "pop2" ~ "2", "pop3" ~ "3")

####make scatterplot, boxplot####
plot2 <- tickwts %>% 
  #filter(population=="pop1" | population =="pop2") %>%
  ggplot(aes(x=population,
             y=weight_mg)) +
  geom_point(size = 3) 
plot2

plot3 <- tickwts %>% 
  ggplot(aes(x=population,
             y=weight_mg)) +
  geom_boxplot()
plot3

####T-test and T-statistic for pop1,pop2####

#adding in saving function

sink(file = "../output/ttest.txt")
ttest <- t.test(pop1,pop3)
ttest
tstat <- ttest$statistic
tstat
sink(file = NULL)

####power calculation####
pwr.t.test(100000,0.1,0.05)

####t-distribution graphic####
#base R way
plot(function(x) dt(x, df = 198), -4, 4, ylim = c(0, 0.7),
     main = "t-distribution", yaxs = "i", xlab= "stdev")
abline(v=1, col="darkgreen")
abline(v=-1, col="darkgreen")
abline(v=-2, col="green")
abline(v=2,col="green", )
       abline(v=tstat, col="red",lty = 4)

       
#tidyverse way
       
#adding in .pdf generation

pdf(file = "../output/tdist.pdf", width = 6, height = 4)
x <- seq(-4, 4, length=100)     
y <-  dt(x, df = 198)      

stdt <- tibble(x,y)

stdtplot <- stdt |> ggplot(aes(x = x, y = y)) +
  geom_line() +
  geom_vline(xintercept = 1, color = "darkblue")+
  geom_vline(xintercept = -1, color = "darkblue")+
  geom_vline(xintercept = 2, color = "lightblue")+
  geom_vline(xintercept = -2, color = "lightblue")+
  geom_vline(xintercept = tstat, color = "orange") +
   theme_bw()
stdtplot
dev.off()

pdf(file = "../output/comboplot.pdf", width = 8, height = 4)
ggarrange(norm_dist, stdtplot)
dev.off()




```