---
title: "human_biting"
output: html_document
date: "2024-09-23"
---

```{r setup, include=FALSE}

#install packages
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("googlesheets4")) install.packages("googlesheets4")
if (!require("janitor")) install.packages("janitor")
if (!require("lubridate")) install.packages("lubridate")
if (!require("readxl")) install.packages("readxl")
if (!require("remotes")) install.packages("remotes")
#remotes::install_github("trobinj/trtools")

#set working directory to present directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()
#load libraries
library(tidyverse)
library(googlesheets4)
library(janitor)
library(lubridate)
library(readxl)

knitr::opts_chunk$set(echo = TRUE)
```
```{r import data}

hb_data <- read_excel("../data/Copy of Master_Naturalist_Donated_Ticks.xlsx", 
    sheet = "Sheet1", col_types = c("text", 
        "date", "numeric", "numeric", "numeric", 
        "text", "text", "text", "numeric", 
        "numeric", "numeric", "text", "text", 
        "text", "text", "text"), na = "NA")
View(hb_data)
body_sites <- levels(as.factor(hb_data$`Body site`))
```
```{r data wrangle}
#piped_version
hb_data_wrangled <- hb_data |>
  clean_names() |>
  select(date:label, species_name:life_stage_name) |>
  mutate(
    new_body_site = case_when(
    str_detect(body_site, "[Ss]tomach|[Bb]ack|abdomen|chest|waist|.*[Ss]houlder|U_body") == "TRUE" ~ "TRUNK",
    str_detect(body_site, "ankle|.*[Cc]alf|foot|[Gg]roin|knee|[LR]_buttcheek|shin|.*_?[Tt]high|.*[Ll]eg|.*[Hh]ip") == "TRUE" ~ "LEG",
    str_detect(body_site, ".*[Hh]ead|chin|Jaw|[Nn]eck|.*[Ee]ar|.*[Cc]heek") == "TRUE" ~ "HEAD",
    str_detect(body_site, ".*[Aa]rm.*|.*[Ee]lbow|.*[Hh]and|.*[Ww]rist|finger") == "TRUE" ~ "ARM",
    str_detect(body_site, "[LR]") == "TRUE" ~ NA,
    TRUE ~ as.character(body_site)
    ),
    new_life_stage = case_when(
      str_detect(life_stage_name, "Larva|Nymph") == "TRUE" ~ "Juvenile",
      TRUE ~ as.character(life_stage_name)
         )
  )
levels(as.factor(hb_data_wrangled$new_body_site))
#look at NAs in dataframe
hb_data_wrangled |>
  filter(if_any(everything(), is.na))

#careful.  There are also "NA" strings in dataframe
hb_data_wrangled |>
  filter(if_any(everything(), ~stringr::str_detect(., "NA")))

```
```{r body region histogram}
hb_data_wrangled |>
  filter(!is.na(new_body_site)) |>
  ggplot(aes(x=new_body_site, fill = species_name)) +
  geom_bar() +
  facet_grid(new_life_stage~year)


hb_data_wrangled |>
  filter(!is.na(new_body_site)) |>
  ggplot(aes(x=new_body_site, y= year, fill = species_name)) +
  geom_tile() 

```
```{r heatmap}
df <- hb_data_wrangled |>
  group_by(new_body_site) |>
  count(species_name) 
df

df2 <- df |>
  group_by(new_body_site) |>
  summarize(sum = sum(n))
df2

df3 <- left_join(df,df2) |>
  mutate(
    prop = n/sum
  )
df3

df3 |>
  filter(!is.na(new_body_site)) |>
  ggplot(aes(x=new_body_site, y= species_name, fill = prop)) +
  geom_tile() 

```
```{r contingency table}

contab <- function(x){
  hb_data_wrangled |>
  filter(!is.na(species_name), !is.na(new_body_site)) |>
  filter(life_stage_name %in% {{x}}) |>
  group_by(species_name,new_body_site)|>
  summarize(count = n()) |>
  pivot_wider(names_from = species_name, values_from = count, values_fill = list(count=0)) |>
  column_to_rownames(var = "new_body_site")
}

#
ctable_all <- contab(life_stage_name) |>
  chisq.test()
ctable_all
library(corrplot)
corrplot(ctable_all$residuals, is.cor = FALSE)

ctable_adult <- contab(c("Female", "Male")) |>
  chisq.test()
ctable_adult
library(corrplot)
corrplot(ctable_adult$residuals, is.cor = FALSE)

ctable_juv <- contab(c("Nymph","Larva")) |>
  chisq.test()
ctable_juv
library(corrplot)
corrplot(ctable_juv$residuals, is.cor = FALSE)

contrib <- 100*chisq$residuals^2/chisq$statistic
round(contrib, 3)

corrplot(contrib, is.cor = FALSE)
```



