---
title: "mealworms"
output: html_document
date: "2024-11-06"
---

```{r setup, include=FALSE}
#install packages
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("googlesheets4")) install.packages("googlesheets4")
if (!require("janitor")) install.packages("janitor")
if (!require("lubridate")) install.packages("lubridate")
if (!require("readxl")) install.packages("readxl")
if (!require("remotes")) install.packages("remotes")

#load libraries
library(tidyverse)
library(googlesheets4)
library(janitor)
library(lubridate)
library(readxl)

#set working directory to present directory
setwd(dirname(rstudioapi::getActiveDocumentContext()$path))
getwd()

knitr::opts_chunk$set(echo = TRUE)
```
```{r data import}
data <- read_excel("../data/Copy of MW_Biosolid_PILOT_22March2024.xlsx", 
    sheet = "MW3_Biosolid_PILOT_22March2024", 
    col_types = c("date", "numeric", "numeric", 
        "text", "numeric", "numeric", "numeric", 
        "numeric", "numeric", "text", "numeric", 
        "numeric", "text", "text", "text", 
        "numeric", "numeric", "numeric")) |>
  select(Collection_Date:10) |>
  clean_names() |>
  mutate(notes = x10) |>
  select(!x10) 
```
```{r ggplot}
data |>
  filter(collection_number == 1) |>
ggplot(aes(x = collection_number, y = larval_wt_total)) +
  geom_point() +
  geom_boxplot()

```


